/*
 * Created on 2020-02-08 ( Time 19:53:19 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.sdx.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.sdx.entity.Patient;
import com.sdx.service.BaseEntityService;
import org.springframework.beans.factory.annotation.Autowired;
import com.sdx.repository.PatientRepository;

//import com.sdx.business.service.PatientServiceMapper;
import org.springframework.stereotype.Component;
//import org.springframework.transaction.annotation.Transactional;
import org.springframework.stereotype.Service;
import com.sdx.entity.BaseEntity;
import com.sdx.entity.HomeCare;

import org.bson.types.ObjectId;

/**
 * Implementation of PatientService
 */
@Component
@Service
public class PatientServiceImpl implements BaseEntityService {

	@Autowired
	private HomeCareServiceImpl homeCareService; 

	
	@Autowired
	private PatientRepository patientRepository;
	
	@Autowired
	private DoctorServiceImpl doctorServiceImpl;
	
	@Autowired
	private DiagnosisServiceImpl diagnosisServiceImpl;
	
	@Autowired
	private NurseServiceImpl nurseServiceImpl;

	@Override
	public BaseEntity findById(String id) {

		return this.patientRepository.findById(id).get();
	}
	
	

	@Override
	public List<BaseEntity> findAll() {
		List<BaseEntity> patient = new ArrayList<>();
		System.out.println("Patient FIND >>" + patient); 

		patientRepository.findAll().forEach(patCare -> {
			patCare.setIdrep(patCare._id.toString());
			patient.add(patCare);
		});
		System.out.println("FINDALL DEPT>>>>>>>>>" + patient);
		return patient;
	}

	@Override
	public BaseEntity save(BaseEntity entity) {
		if (entity instanceof Patient) {
			Patient patient = (Patient) entity;
			return this.patientRepository.save(patient);
		}
		return null;
	}

	public BaseEntity saveByRef(BaseEntity entity) {
		if (entity instanceof Patient) {
			Patient patient = (Patient) entity;
			patient.setDoctor(doctorServiceImpl.getById(patient.getDoctor().getIdRep()));
			patient.setNurse(nurseServiceImpl.getById(patient.getNurse().getIdRep()));
			patient.setDiagnosis(diagnosisServiceImpl.getById(patient.getDiagnosis().getIdRep()));
			patient.setHomecare(homeCareService.getById(patient.getHomecare().getIdrep()));
			System.out.println("SAVEREF//////////////////////"+patient);
			return this.patientRepository.save(patient);
		}
		return null;
	}
	@Override
	public void delete(String id) {
		patientRepository.deleteById(id);
	}

	@Override
	public BaseEntity update(String id, BaseEntity entity) {
		System.out.println("I n UPDATE METHOD");
		if (entity instanceof Patient) {
			Patient pat = (Patient) entity;
			
			pat.setDoctor(doctorServiceImpl.getById(pat.getDoctor().getIdRep()));
			pat.setNurse(nurseServiceImpl.getById(pat.getNurse().getIdRep()));
			pat.setDiagnosis(diagnosisServiceImpl.getById(pat.getDiagnosis().getIdRep()));
			pat.setHomecare(homeCareService.getById(pat.getHomecare().getIdrep()));
			pat.set_id(new ObjectId(id));
			return this.patientRepository.save(pat);
		}
		return null;

	}
	public Patient findByPatientName(String patientName) {
		// TODO Auto-generated method stub
		Patient patient = (Patient) this.patientRepository.findByPatientName(patientName);
		System.out.println("ID OF patient IS:::::::::" + patient.get_id().toString());
		patient.setIdrep(patient.get_id().toString());
		System.out.println("patient ::::::::::::" + patient);
		return patient;
	}
	
	public ArrayList<Object> findAllPatientName() {
		ArrayList<Object> patient = new ArrayList<>();
		patientRepository.findAll().forEach(patientRep -> {
		patient.add(patientRep.getName());
		
		System.out.println("Patient SERVICE CLASSS "+patient);

		});
		return patient;
	}
}