/*
 * Created on 2020-02-08 ( Time 19:53:19 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.sdx.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.sdx.entity.HomeCare;

import com.sdx.service.BaseEntityService;
import org.springframework.beans.factory.annotation.Autowired;

import com.sdx.repository.DoctorRepository;


//import com.sdx.business.service.HomeCareServiceMapper;
import org.springframework.stereotype.Component;
//import org.springframework.transaction.annotation.Transactional;
import org.springframework.stereotype.Service;
import com.sdx.entity.BaseEntity;
import com.sdx.entity.Doctor;

import org.bson.types.ObjectId;


@Component
@Service
public class DoctorServiceImpl implements BaseEntityService {

	@Autowired
	private DoctorRepository doctorRepository;

	@Override
	public BaseEntity findById(String id) {
		Doctor doctor = (Doctor) this.doctorRepository.findByDoctorId(id);
		doctor.setIdRep(id);
		System.out.println("find by id : " + doctor);
		return doctor;
	}
	
	public Doctor getById(String id) {
		Doctor doctor = doctorRepository.findById(id).orElse(null);
		return doctor;
	}


	@Override
	public List<BaseEntity> findAll() {
		List<BaseEntity> doctor = new ArrayList<>();
		System.out.println("CARE FIND >>" + doctor);
		//homeCareRepository.findAll().forEach(homeCare::add);
		doctorRepository.findAll().forEach(care -> {
			care.setIdRep(care._id.toString());
			doctor.add(care);
			System.out.println("FINDALL DEPT>>>>>>>>>"+doctor);
		});
		
		return doctor; 
	}

	
	public ArrayList<Object> findAllDoctor() {
		ArrayList<Object> doctor = new ArrayList<>();
		doctorRepository.findAll().forEach(doctortRep -> {
		doctor.add(doctortRep.getDoctorName());
		
		System.out.println("DOCTOR SERVICE CLASSS "+doctor);

		});
		return doctor;
	}
	

	public Doctor findByDoctorName(String doctorName) {
		// TODO Auto-generated method stub
		Doctor doctor = (Doctor) this.doctorRepository.findByDoctorName(doctorName);
		System.out.println("ID OF Doctor IS:::::::::" + doctor.get_id().toString());
		doctor.setIdRep(doctor.get_id().toString());
		System.out.println("doctor ::::::::::::" + doctor);
		return doctor;
	}
	
	
	@Override
	public BaseEntity save(BaseEntity entity) {
		if (entity instanceof Doctor) {
			Doctor doctor = (Doctor) entity;
			return this.doctorRepository.save(doctor);
		}
		return null;
	}

	@Override
	public BaseEntity update(String id, BaseEntity entity) {
		if (entity instanceof Doctor) {
			Doctor doctor = (Doctor) entity;
			doctor.set_id(new ObjectId(id));
			
			return this.doctorRepository.save(doctor);
		}
		return null;
	}

	@Override
	public void delete(String id) {
		doctorRepository.deleteById(id);
	}

}
