/*
 * Created on 2020-02-08 ( Time 19:53:19 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.sdx.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.sdx.entity.Patient;
import com.sdx.service.BaseEntityService;
import org.springframework.beans.factory.annotation.Autowired;

import com.sdx.repository.NurseRepository;
import com.sdx.repository.PatientRepository;

//import com.sdx.business.service.PatientServiceMapper;
import org.springframework.stereotype.Component;
//import org.springframework.transaction.annotation.Transactional;
import org.springframework.stereotype.Service;
import com.sdx.entity.BaseEntity;
import com.sdx.entity.Diagnosis;
import com.sdx.entity.HomeCare;
import com.sdx.entity.Nurse;

import org.bson.types.ObjectId;

/**
 * Implementation of PatientService
 */
@Component
@Service
public class NurseServiceImpl implements BaseEntityService {

	@Autowired
	private NurseRepository nurseRepository;

		

	
	public Nurse getById(String id) {
		Nurse nurseId = nurseRepository.findById(id).orElse(null);
		return nurseId;
	}
	
	@Override
	public BaseEntity findById(String id) {
		Nurse nurse = (Nurse) this.nurseRepository.findByNurseId(id);
		nurse.setIdRep(id);
		System.out.println("find by id : " + nurse);
		return nurse;
	}
	
	


	@Override
	public List<BaseEntity> findAll() {
		List<BaseEntity> nurse = new ArrayList<>();
		System.out.println("NURSE FIND >>" + nurse);
		
		nurseRepository.findAll().forEach(patCare -> {
			patCare.setIdRep(patCare._id.toString());
			nurse.add(patCare);
		});
		System.out.println("FINDALL NURSES>>>>>>>>>"+nurse);
		return nurse; 
	}
	
	
	public ArrayList<Object> findAllNurses() {
		ArrayList<Object> Nurses = new ArrayList<>();
		nurseRepository.findAll().forEach(NurseRep -> {
			Nurses.add(NurseRep.getName());
			System.out.println("name is :::: " +Nurses);
		});
		return Nurses;
	}
	
	
	public Nurse findByNurseName(String nurseName) {
		// TODO Auto-generated method stub
		Nurse nurse = (Nurse) this.nurseRepository.findByNurseName(nurseName);
		System.out.println("ID OF Nurse IS:::::::::" + nurse.get_id().toString());
		nurse.setIdRep(nurse.get_id().toString());
		System.out.println("department ::::::::::::" + nurse);
		return nurse;
	}
	
	
	
    @Override
	public BaseEntity save(BaseEntity entity) {
	if (entity instanceof Nurse) {
		Nurse nurse=(Nurse) entity;
    return this.nurseRepository.save(nurse);
	}
    return null;
    }
	
        


	@Override
	public void delete (String id) {
		nurseRepository.deleteById(id);
    }

	@Override
	public BaseEntity update(String id, BaseEntity entity) {
		System.out.println("I n UPDATE METHOD");
			if (entity instanceof Nurse) {
				Nurse  pat = (Nurse) entity;
				pat.set_id(new ObjectId(id));
				return this.nurseRepository.save(pat);
			}
			return null;

	}



	}
