/*
 * Created on 2020-02-08 ( Time 20:03:34 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.sdx.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.sdx.entity.Telemedicine;


import java.util.Date;
import com.sdx.service.BaseEntityService;
import org.springframework.beans.factory.annotation.Autowired;
import com.sdx.repository.TelemedicineRepository;

//import com.sdx.business.service.TelemedicineServiceMapper;
import org.springframework.stereotype.Component;
//import org.springframework.transaction.annotation.Transactional;
import org.springframework.stereotype.Service;
import com.sdx.entity.BaseEntity;
import org.bson.types.ObjectId;

/**
 * Implementation of TelemedicineService
 */
@Component
@Service
public class TelemedicineServiceImpl implements BaseEntityService {

	@Autowired
	private TelemedicineRepository telemedicineRepository;

		
	@Override
	public BaseEntity findById(String id) {
		
		Telemedicine users = (Telemedicine) this.telemedicineRepository.findByTelemedicineId(id);
		users.setIdRep(id);
	
        return users;
	}

	@Override
	public List<BaseEntity> findAll() {
    List<BaseEntity> telemedicine = new ArrayList<>();
	telemedicineRepository.findAll().forEach(telemedicine::add);
	return telemedicine;
	}
	
    @Override
	public BaseEntity save(BaseEntity entity) {
	if (entity instanceof Telemedicine) {
	Telemedicine telemedicine=(Telemedicine) entity;
    return this.telemedicineRepository.save(telemedicine);
	}
    return null;
    }
	
        


	public BaseEntity update(ObjectId _id,BaseEntity entity) {
	if (entity instanceof Telemedicine) {
	Telemedicine telemedicine=(Telemedicine) entity;
    telemedicine.set_id(_id);
    return this.telemedicineRepository.save(telemedicine);
	}
    return null;
	}

	@Override
	public void delete (String id) {
    telemedicineRepository.deleteById(id);
    }

	@Override
	public BaseEntity update(String id, BaseEntity entity) {
		// TODO Auto-generated method stub
		return null;
	}

	}
