/*
 * Created on 2020-02-13 ( Time 16:15:54 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.sdx.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.sdx.entity.EventDistributor;

import com.sdx.service.BaseEntityService;
import org.springframework.beans.factory.annotation.Autowired;
import com.sdx.repository.EventDistributorRepository;

//import com.sdx.business.service.EventDistributorServiceMapper;
import org.springframework.stereotype.Component;
//import org.springframework.transaction.annotation.Transactional;
import org.springframework.stereotype.Service;
import com.sdx.entity.BaseEntity;
import org.bson.types.ObjectId;

/**
 * Implementation of EventDistributorService
 */
@Component
@Service
public class EventDistributorServiceImpl implements BaseEntityService {

	@Autowired
	private EventDistributorRepository eventDistributorRepository;

	@Override
	public BaseEntity findById(String id) {

		return this.eventDistributorRepository.findById(id).get();
	}

	@Override
	public List<BaseEntity> findAll() {
		List<BaseEntity> eventDistributor = new ArrayList<>();
		eventDistributorRepository.findAll().forEach(eventDistributor::add);
		return eventDistributor;
	}

	@Override
	public BaseEntity save(BaseEntity entity) {
		if (entity instanceof EventDistributor) {
			EventDistributor eventDistributor = (EventDistributor) entity;
			return this.eventDistributorRepository.save(eventDistributor);
		}
		return null;
	}

	@Override
	public BaseEntity update(String _id, BaseEntity entity) {
		if (entity instanceof EventDistributor) {
			EventDistributor eventDistributor = (EventDistributor) entity;
			eventDistributor.set_id(new ObjectId(_id));
			return this.eventDistributorRepository.save(eventDistributor);
		}
		return null;
	}

	@Override
	public void delete(String id) {
		eventDistributorRepository.deleteById(id);
	}

	public BaseEntity update(ObjectId _id, BaseEntity entity) {
		// TODO Auto-generated method stub
		return null;
	}

}
