
/*
 * Java bean class
 * Created on 2020-02-08 ( Date ISO 2020-02-08 - Time 19:52:09 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */

package com.sdx.entity;

import java.io.Serializable;


import org.springframework.data.annotation.Id;

import org.springframework.data.mongodb.core.mapping.DBRef;

import org.springframework.data.mongodb.core.mapping.Document;
import com.sdx.entity.BaseEntity;
import org.bson.types.ObjectId;

@Document(collection = "nurses")
public class Nurse implements Serializable,BaseEntity
{
    private static final long serialVersionUID = 1L;
    @Id
	public ObjectId _id;
    private String idRep;
    private String name;
   
    /**
     * Default constructor
     */
    public Nurse(){
    
        super();
    }
    
    public Nurse(String id) {
		setIdRep(id);

	}

    public ObjectId get_id() {
		return _id;
	}

	public void set_id(ObjectId _id) {
		this._id = _id;
	}

    
    /**
     * Set the "idrep" field value
     * @param idrep
     */
    public void setIdRep( String idrep ){
    
        this.idRep = idrep;
    }
        
    /**
     * Get the "idrep" field value
     * @return the field value
     */
    public String getIdRep(){

        return this.idRep;
    }
        
    /**
     * Set the "name" field value
     * @param name
     */
    public void setName( String name ){
    
        this.name = name;
    }
        
    /**
     * Get the "name" field value
     * @return the field value
     */
    public String getName(){

        return this.name;
    }
        
    /**
     * Set the "location" field value
     * @param location
     */
   
    
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idRep);
		/*
		 * sb.append("|"); sb.append(name); sb.append("|"); sb.append(location);
		 * sb.append("|"); sb.append(roomTemp); sb.append("|"); sb.append(roomHumidity);
		 * sb.append("|"); sb.append(lightOnOff); sb.append("|"); sb.append(frontDoor);
		 */
        return sb.toString(); 
    } 


}