
/*
 * Java bean class
 * Created on 2020-02-08 ( Date ISO 2020-02-08 - Time 19:52:10 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */

package com.sdx.entity;

import java.io.Serializable;

import org.springframework.data.annotation.Id;

import org.springframework.data.mongodb.core.mapping.DBRef;

import org.springframework.data.mongodb.core.mapping.Document;
import com.sdx.entity.BaseEntity;
import org.bson.types.ObjectId;

@Document(collection = "patients")
public class Patient implements Serializable, BaseEntity {
	private static final long serialVersionUID = 1L;
	@Id
	public ObjectId _id;
	private String idRep;
	private String name;
	private String gender;
	private String dob;
	private String height;
	private String weight;
	private String status;
	private String location;

	private int floor = -1;
	private int room = -1;

	@DBRef
	private HomeCare homecare;

	@DBRef
	private Doctor doctor;

	@DBRef
	private Diagnosis diagnosis;

	@DBRef
	private Nurse nurse;

	/**
	 * Default constructor
	 */
	public Patient() {
		super();
	}

	public ObjectId get_id() {
		return _id;
	}

	public void set_id(ObjectId _id) {
		this._id = _id;
	}

	public HomeCare getHomecare() {
		return homecare;
	}

	public void setHomecare(HomeCare homecare) {
		this.homecare = homecare;
	}

	public int getFloor() {
		return floor;
	}

	public void setFloor(int floor) {
		this.floor = floor;
	}

	public int getRoom() {
		return room;
	}

	public void setRoom(int room) {
		this.room = room;
	}

	/**
	 * Set the "idrep" field value
	 * 
	 * @param idrep
	 */
	public void setIdrep(String idrep) {

		this.idRep = idrep;
	}

	public Diagnosis getDiagnosis() {
		return diagnosis;
	}

	public void setDiagnosis(Diagnosis diagnosis) {
		this.diagnosis = diagnosis;
	}

	public Doctor getDoctor() {
		return doctor;
	}

	public void setDoctor(Doctor doctor) {
		this.doctor = doctor;
	}

	public Nurse getNurse() {
		return nurse;
	}

	public void setNurse(Nurse nurse) {
		this.nurse = nurse;
	}

	/**
	 * Get the "idrep" field value
	 * 
	 * @return the field value
	 */
	public String getIdrep() {

		return this.idRep;
	}

	/**
	 * Set the "name" field value
	 * 
	 * @param name
	 */
	public void setName(String name) {

		this.name = name;
	}

	/**
	 * Get the "name" field value
	 * 
	 * @return the field value
	 */
	public String getName() {

		return this.name;
	}

	/**
	 * Set the "gender" field value
	 * 
	 * @param gender
	 */
	public void setGender(String gender) {

		this.gender = gender;
	}

	/**
	 * Get the "gender" field value
	 * 
	 * @return the field value
	 */
	public String getGender() {

		return this.gender;
	}

	/**
	 * Set the "dob" field value
	 * 
	 * @param dob
	 */
	public void setDob(String dob) {

		this.dob = dob;
	}

	/**
	 * Get the "dob" field value
	 * 
	 * @return the field value
	 */
	public String getDob() {

		return this.dob;
	}

	/**
	 * Set the "height" field value
	 * 
	 * @param height
	 */
	public void setHeight(String height) {

		this.height = height;
	}

	/**
	 * Get the "height" field value
	 * 
	 * @return the field value
	 */
	public String getHeight() {

		return this.height;
	}

	/**
	 * Set the "weight" field value
	 * 
	 * @param weight
	 */
	public void setWeight(String weight) {

		this.weight = weight;
	}

	/**
	 * Get the "weight" field value
	 * 
	 * @return the field value
	 */
	public String getWeight() {

		return this.weight;
	}

	public String getLocation() {
		return location;
	}

	public void setLocation(String location) {
		this.location = location;
	}

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(idRep);
		/*
		 * sb.append("|"); sb.append(name); sb.append("|"); sb.append(gender);
		 * sb.append("|"); sb.append(dob); sb.append("|"); sb.append(height);
		 * sb.append("|"); sb.append(weight); sb.append("|"); sb.append(diagnosis);
		 * sb.append("|"); sb.append(doctor); sb.append("|"); sb.append(nurse);
		 * sb.append("|"); sb.append(location); sb.append("|");
		 * sb.append(homecare.getName());
		 */

		return sb.toString();
	}

}