/*
 * Created on 2020-01-03 ( Time 12:16:36 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.sdx.service;

import java.util.List;

import org.bson.types.ObjectId;

import com.sdx.entity.BaseEntity;

public interface BaseEntityService {
	BaseEntity findById(String id);

	List<BaseEntity> findAll();

	BaseEntity save(BaseEntity entity);

	BaseEntity update(String id, BaseEntity entity);

	void delete(String id);

}
