
/*
 * Java bean class
 * Created on 2020-02-08 ( Date ISO 2020-02-08 - Time 19:52:09 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */

package com.sdx.entity;

import java.io.Serializable;

import org.springframework.data.annotation.Id;

import org.springframework.data.mongodb.core.mapping.Document;
import com.sdx.entity.BaseEntity;
import org.bson.types.ObjectId;

@Document(collection = "doctor")
public class Doctor implements Serializable, BaseEntity {
	private static final long serialVersionUID = 1L;
	@Id
	public ObjectId _id;
	private String idRep;
	private String doctorName;
	private String specialist;
	private String shift;
	private String availability;

	public String getShift() {
		return shift;
	}

	public void setShift(String shift) {
		this.shift = shift;
	}

	public String getAvailability() {
		return availability;
	}

	public void setAvailability(String availability) {
		this.availability = availability;
	}

	public Doctor() {
		super();
	}

	public Doctor(String id) {
		setIdRep(id);
	}

	public ObjectId get_id() {
		return _id;
	}

	public void set_id(ObjectId _id) {
		this._id = _id;
	}

	public String getIdRep() {
		return idRep;
	}

	public void setIdRep(String idRep) {
		this.idRep = idRep;
	}

	public String getDoctorName() {
		return doctorName;
	}

	public void setDoctorName(String doctorName) {
		this.doctorName = doctorName;
	}

	public String getSpecialist() {
		return specialist;
	}

	public void setSpecialist(String specialist) {
		this.specialist = specialist;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public String toString() {
		StringBuffer sb = new StringBuffer();
		sb.append(idRep);
		/*
		 * sb.append("|"); sb.append(doctorName); sb.append("|"); sb.append(specialist);
		 * sb.append("|"); sb.append(shift); sb.append("|"); sb.append(availability);
		 */
		return sb.toString();
	}

}