
/*
 * Java bean class
 * Created on 2020-02-08 ( Date ISO 2020-02-08 - Time 20:02:08 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */

package com.sdx.entity;

import java.io.Serializable;

import java.util.Date;

import org.springframework.data.annotation.Id;

import org.springframework.data.mongodb.core.mapping.DBRef;

import org.springframework.data.mongodb.core.mapping.Document;
import com.sdx.entity.BaseEntity;
import org.bson.types.ObjectId;

@Document(collection = "medics")
public class Telemedicine implements Serializable,BaseEntity
{
    private static final long serialVersionUID = 1L;
    @Id
	public ObjectId _id;
    private String idRep;
	private String name;
    private Integer deviceId;
    private String type;
    private String manufacturer;
    private String serialNo;
    private String address;
    private String caliberatedDate;

    /**
     * Default constructor
     */
    
    
    public Telemedicine(){
    
        super();
    }

    public ObjectId get_id() {
		return _id;
	}

	public void set_id(ObjectId _id) {
		this._id = _id;
	}

	  public String getIdRep() {
			return idRep;
		}

		public void setIdRep(String idRep) {
			this.idRep = idRep;
		}

		public String getAddress() {
			return address;
		}

		public void setAddress(String address) {
			this.address = address;
		}
    /**
     * Set the "name" field value
     * @param name
     */
    public void setName( String name ){
    
        this.name = name;
    }
        
    /**
     * Get the "name" field value
     * @return the field value
     */
    public String getName(){

        return this.name;
    }
        
    /**
     * Set the "deviceId" field value
     * @param deviceId
     */
    public void setDeviceId( Integer deviceId ){
    
        this.deviceId = deviceId;
    }
        
    /**
     * Get the "deviceId" field value
     * @return the field value
     */
    public Integer getDeviceId(){

        return this.deviceId;
    }
        
    /**
     * Set the "type" field value
     * @param type
     */
    public void setType( String type ){
    
        this.type = type;
    }
        
    /**
     * Get the "type" field value
     * @return the field value
     */
    public String getType(){

        return this.type;
    }
        
    /**
     * Set the "manufacturer" field value
     * @param manufacturer
     */
    public void setManufacturer( String manufacturer ){
    
        this.manufacturer = manufacturer;
    }
        
    /**
     * Get the "manufacturer" field value
     * @return the field value
     */
    public String getManufacturer(){

        return this.manufacturer;
    }
        
    /**
     * Set the "serialNo" field value
     * @param serialNo
     */
    public void setSerialNo( String serialNo ){
    
        this.serialNo = serialNo;
    }
        
    /**
     * Get the "serialNo" field value
     * @return the field value
     */
    public String getSerialNo(){

        return this.serialNo;
    }
        
    /**
     * Set the "sPAddress" field value
     * @param sPAddress
     */
    public void setSPAddress( String sPAddress ){
    
        this.address = sPAddress;
    }
        
    /**
     * Get the "sPAddress" field value
     * @return the field value
     */
    public String getSPAddress(){

        return this.address;
    }
        
    /**
     * Set the "caliberatedDate" field value
     * @param caliberatedDate
     */
    public void setCaliberatedDate( String caliberatedDate ){
    
        this.caliberatedDate = caliberatedDate;
    }
        
    /**
     * Get the "caliberatedDate" field value
     * @return the field value
     */
    public String getCaliberatedDate(){

        return this.caliberatedDate;
    }
        
    /**
     * Set the "caliberationDate" field value
     * @param caliberationDate
     */
    public void setCaliberationDate( String caliberationDate ){
    
        this.caliberatedDate = caliberationDate;
    }
        
    /**
     * Get the "caliberationDate" field value
     * @return the field value
     */
    public String getCaliberationDate(){

        return this.caliberatedDate;
    }
    
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(name);
        sb.append("|");
        sb.append(deviceId);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(manufacturer);
        sb.append("|");
        sb.append(serialNo);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(caliberatedDate);
        sb.append("|");
        sb.append(caliberatedDate);
        return sb.toString(); 
    } 


}