
/*
 * Java bean class
 * Created on 2020-02-08 ( Date ISO 2020-02-08 - Time 19:52:09 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */

package com.sdx.entity;

import java.io.Serializable;


import org.springframework.data.annotation.Id;

import org.springframework.data.mongodb.core.mapping.DBRef;

import org.springframework.data.mongodb.core.mapping.Document;
import com.sdx.entity.BaseEntity;
import org.bson.types.ObjectId;

@Document(collection = "homeCares")
public class HomeCare implements Serializable,BaseEntity
{
    private static final long serialVersionUID = 1L;
    @Id
	public ObjectId _id;
    private String idrep;
    private String name;
    private String location;
    private String roomTemp;
    private String roomHumidity;
    private String lightOnOff;
    private String frontDoor;
    

    /**
     * Default constructor
     */
    public HomeCare(){
    
        super();
    }
    public HomeCare(String id) {
		setIdrep(id);

	}

    public ObjectId get_id() {
		return _id;
	}

	public void set_id(ObjectId _id) {
		this._id = _id;
	}

    
    /**
     * Set the "idrep" field value
     * @param idrep
     */
    public void setIdrep( String idrep ){
    
        this.idrep = idrep;
    }
        
    /**
     * Get the "idrep" field value
     * @return the field value
     */
    public String getIdrep(){

        return this.idrep;
    }
        
    /**
     * Set the "name" field value
     * @param name
     */
    public void setName( String name ){
    
        this.name = name;
    }
        
    /**
     * Get the "name" field value
     * @return the field value
     */
    public String getName(){

        return this.name;
    }
        
    /**
     * Set the "location" field value
     * @param location
     */
    public void setLocation( String location ){
    
        this.location = location;
    }
        
    /**
     * Get the "location" field value
     * @return the field value
     */
    public String getLocation(){

        return this.location;
    }
        
    /**
     * Set the "roomTemp" field value
     * @param roomTemp
     */
    public void setRoomTemp( String roomTemp ){
    
        this.roomTemp = roomTemp;
    }
        
    /**
     * Get the "roomTemp" field value
     * @return the field value
     */
    public String getRoomTemp(){

        return this.roomTemp;
    }
        
    /**
     * Set the "roomHumidity" field value
     * @param roomHumidity
     */
    public void setRoomHumidity( String roomHumidity ){
    
        this.roomHumidity = roomHumidity;
    }
        
    /**
     * Get the "roomHumidity" field value
     * @return the field value
     */
    public String getRoomHumidity(){

        return this.roomHumidity;
    }
        
    /**
     * Set the "lightOnOff" field value
     * @param lightOnOff
     */
    public void setLightOnOff( String lightOnOff ){
    
        this.lightOnOff = lightOnOff;
    }
        
    /**
     * Get the "lightOnOff" field value
     * @return the field value
     */
    public String getLightOnOff(){

        return this.lightOnOff;
    }
        
    /**
     * Set the "frontDoor" field value
     * @param frontDoor
     */
    public void setFrontDoor( String frontDoor ){
    
        this.frontDoor = frontDoor;
    }
        
    /**
     * Get the "frontDoor" field value
     * @return the field value
     */
    public String getFrontDoor(){

        return this.frontDoor;
    }
    
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(idrep);
		/*
		 * sb.append("|"); sb.append(name); sb.append("|"); sb.append(location);
		 * sb.append("|"); sb.append(roomTemp); sb.append("|"); sb.append(roomHumidity);
		 * sb.append("|"); sb.append(lightOnOff); sb.append("|"); sb.append(frontDoor);
		 */
        return sb.toString(); 
    } 


}