/*
 * Created on 2020-02-08 ( Time 19:53:19 )
 * Generated by Telosys Tools Generator ( version 3.1.2 )
 */
package com.sdx.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.sdx.entity.HomeCare;
import com.sdx.entity.Nurse;
import com.sdx.service.BaseEntityService;
import org.springframework.beans.factory.annotation.Autowired;
import com.sdx.repository.HomeCareRepository;

//import com.sdx.business.service.HomeCareServiceMapper;
import org.springframework.stereotype.Component;
//import org.springframework.transaction.annotation.Transactional;
import org.springframework.stereotype.Service;
import com.sdx.entity.BaseEntity;
import com.sdx.entity.Diagnosis;

import org.bson.types.ObjectId;

/**
 * Implementation of HomeCareService
 */
@Component
@Service
public class HomeCareServiceImpl implements BaseEntityService {

	@Autowired
	private HomeCareRepository homeCareRepository;

	@Override
	public BaseEntity findById(String id) {
		HomeCare HomeCare = (HomeCare) this.homeCareRepository.findByHomeCareId(id);
		HomeCare.setIdrep(id);
		System.out.println("find by id : " + HomeCare);
		return HomeCare;
	}

	@Override
	public List<BaseEntity> findAll() {
		List<BaseEntity> homeCare = new ArrayList<>();
		System.out.println("CARE FIND >>" + homeCare);
		//homeCareRepository.findAll().forEach(homeCare::add);
		homeCareRepository.findAll().forEach(care -> {
			care.setIdrep(care._id.toString());
			homeCare.add(care);
		});
		System.out.println("FINDALL DEPT>>>>>>>>>"+homeCare);
		return homeCare; 
	}

	@Override
	public BaseEntity save(BaseEntity entity) {
		if (entity instanceof HomeCare) {
			HomeCare homeCare = (HomeCare) entity;
			return this.homeCareRepository.save(homeCare);
		}
		return null;
	}

	@Override
	public BaseEntity update(String id, BaseEntity entity) {
		if (entity instanceof HomeCare) {
			HomeCare homeCare = (HomeCare) entity;
			homeCare.set_id(new ObjectId(id));
			return this.homeCareRepository.save(homeCare);
		}
		return null;
	}

	@Override
	public void delete(String id) {
		homeCareRepository.deleteById(id);
	}
	
	public ArrayList<Object> findAllHomeCare() {
		ArrayList<Object> homeCare = new ArrayList<>();
		homeCareRepository.findAll().forEach(homCareRepo -> {
			homeCare.add(homCareRepo.getName());
			

		});
		return homeCare;
	}
	
	public HomeCare findByHomecareName(String nurseName) {
		// TODO Auto-generated method stub
		HomeCare homecare = (HomeCare) this.homeCareRepository.findByHomecareName(nurseName);
		System.out.println("ID OF Nurse IS:::::::::" + homecare.get_id().toString());
		homecare.setIdrep(homecare.get_id().toString());
		System.out.println("department ::::::::::::" + homecare);
		return homecare;
	}
	public HomeCare getById(String id) {
		HomeCare homecare = homeCareRepository.findById(id).orElse(null);
		return homecare;
	}
	

}
