/*
* Java bean class
* Created on 2020-02-13 ( Date ISO 2020-02-13 - Time 16:15:34 )
* Generated by Telosys Tools Generator ( version 3.1.2 )
*/

package com.sdx.repository;

import org.springframework.data.repository.PagingAndSortingRepository;
import com.sdx.entity.EventDistributor;

import org.springframework.stereotype.Repository;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.data.mongodb.repository.Query;
import com.sdx.entity.BaseEntity;

/**
 * Repository
 *
 * @author Telosys Tools Generator
 *
 */
@Repository
public interface EventDistributorRepository
		extends PagingAndSortingRepository<EventDistributor, String>, MongoRepository<EventDistributor, String> {
	@Query("{'_id' :?0}")
	BaseEntity findByEventDistributionId(String id);
}
