/*
* Java bean class
* Created on 2020-02-08 ( Date ISO 2020-02-08 - Time 19:52:10 )
* Generated by Telosys Tools Generator ( version 3.1.2 )
*/

package com.sdx.repository;

import java.io.Serializable;


import org.springframework.data.repository.PagingAndSortingRepository;
import org.springframework.stereotype.Repository;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.data.mongodb.repository.Query;
import com.sdx.entity.BaseEntity;
import com.sdx.entity.Nurse;


/**
 * Repository
 *
 * @author Telosys Tools Generator
 *
 */
@Repository
public interface NurseRepository extends PagingAndSortingRepository<Nurse, String>,MongoRepository<Nurse, String>
{
	
@Query("{'_id' :?0}")
BaseEntity findByNurseId(String id);

@Query(value = "{'name' :?0 }", fields = "{'_id' :1,'idRep': 1, 'name':1 }")
Nurse findByNurseName(String nurseName);

}
